### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by zzl0** [dbcli/athenacli#13]
I haven't found an easy way to test Athena locally. It seems moto is a good way to test it, but it [doesn't support Athena now](https://github.com/spulec/moto/issues/1524), maybe we can spend some time to make moto support Athena if nobody takes that. Anyway, I'd appreciate it if you have any ideas about testing Athena locally.

**Comment by jashgala** [comment]
+1 for adding Athena support to moto.
It would be a good learning experience as well as resolve our use case.
