### ISSUE TITLE
Add prompt_toolkit 2.0 support

### ISSUE THREAD

**Issue by zzl0** [dbcli/athenacli#14]

**Comment by cedricyau** [comment]
agreed.  pip installing athenacli breaks IPython 7.0.1.

**Comment by GuiMarthe** [comment]
Any followup on this? I'm unable to run `athenacli` together with `pgcli` or `ipython`.

**Comment by zzl0** [comment]
@GuiMarthe thanks for your feedback, I've been busy with work and family stuff recently. 

> Is there an alternative way of installing athenacli isolated from the rest of the python system?

Yes, there are two ways:
1. You can run create a [virtual env](https://virtualenv.pypa.io/en/latest/userguide/#usage) and install `athenacli` in it. 
2. You can also [use docker to install it](https://athenacli.readthedocs.io/en/latest/install.html#docker).

**Comment by tkang007** [comment]
When we need to use athenacli and jupyter together, I think there is no workaround.

Please consider to upgrade prompt-toolkit<2.1.0,>=2.0.0 for compatible with jupyter 1.0.0

Thanks.

**Comment by zzl0** [comment]
@GuiMarthe @tkang007 @cedricyau Hi all, I updated prompt_toolkit to 2.x (`prompt_toolkit>=2.0.6,<3.0.0`). Merry Christmas!
