### ISSUE TITLE
When creating the config file, ask user for mandatory details in that session itself

### ISSUE THREAD

**Issue by jashgala** [dbcli/athenacli#15]
**Current behavior:**

1. When the user runs the program, a check is made to see if a configuration exists.
2. If not, a new configuration file is generated at `~/.athenacli/athenaclirc`.
3. The user has to manually go and update this file for at least the mandatory parameters:
  i.  aws_access_key_id
  ii.  aws_secret_access_key
  iii.  region
  iv. s3_staging_dir

**Proposed behavior:**

1. When the user runs the program for the first time, a check is made to see if a configuration exists.
2. If not, the user is asked to (optionally?) provide the parameters mentioned above.
3. After the user provides the above parameters, the configuration file is generated at `~/.athenacli/athenaclirc` with the above parameters filled with the user's input.

**Comment by zzl0** [comment]
Nice, this would be great for the new user. Would you like to work this feature?

**Comment by jashgala** [comment]
I'll give this a shot!

**Comment by zzl0** [comment]
Great, maybe you can use this [prompt](https://github.com/dbcli/athenacli/blob/2292d9266dcf9ea22d0ab448f148fc17de4efd5f/athenacli/packages/prompt_utils.py#L30) function.

**Comment by jashgala** [comment]
Removing myself as assignee as I am not sure if I'll be able to pick this up anytime soon... If I do get the time I'll work on this and raise a PR.
