### ISSUE TITLE
Running athenacli without configuration changes causes visible Exception

### ISSUE THREAD

**Issue by jashgala** [dbcli/athenacli#18]
When I don't set the values of the AWS configuration parameters, there is an exception thrown in the console causing the CLI to exit.

Perhaps it would be better to have an exception handling routine to handle this scenario. Maybe something similar to what we are trying to do in #15 

At the very least, it would be great to avoid the exception by showing an error message.

<img width="848" alt="missing configuration throws exception" src="https://user-images.githubusercontent.com/16336864/46624653-1df12d00-cb4f-11e8-98c6-f08a78e7629f.png">

**Comment by zzl0** [comment]
Thanks for this issue.

Actually, in the Python community, it's not uncommon to allow visible Exceptions (especially for the developer tools). I'm fine if you want to catch it and print an error message (and ask users to change the config file) and then exit.

But I don't want to catch it and try to recover from it (like, show a prompt and let users input the values) if this isn't the first time to run `athenacli`

**Comment by jashgala** [comment]
(2) would perhaps be better UX than (1)

In the short term, we can do (1) as an immediate fix.

Perhaps when we are solving #15, we can see if it can be implemented in a way where (2) can be supported out of the box.

**Comment by zzl0** [comment]
@jashgala fixed in https://github.com/dbcli/athenacli/pull/20

**Comment by zzl0** [comment]
👍Nice work.
