### ISSUE TITLE
Feature request: Get signed S3 link

### ISSUE THREAD

**Issue by getaaron** [dbcli/athenacli#37]
Currently I can output results to a local file using `tee`, but often I want a signed S3 link to the output.

## Proposal

A new command `download` would output a signed S3 link to the previous query's results.

**Comment by zzl0** [comment]
Sorry, I am not sure what do you mean by signed S3 link. But you can check the `output_location` field in the [PyAthena API](https://github.com/laughingman7743/PyAthena).
