### ISSUE TITLE
Feature request: output cost and size of query

### ISSUE THREAD

**Issue by getaaron** [dbcli/athenacli#39]
Something like:

        submission_date = stats['QueryExecution']['Status']['SubmissionDateTime']
        completion_date = stats['QueryExecution']['Status']['CompletionDateTime']
        execution_time = stats['QueryExecution']['Statistics']['EngineExecutionTimeInMillis']
        data_scanned = stats['QueryExecution']['Statistics']['DataScannedInBytes']
        query_cost = data_scanned / 1000000000000.0 * 5.0

        print('Time: {}, CPU Time: {}ms total, Data Scanned: {}, Cost: ${:,.2f}\n'.format(
            str(completion_date - submission_date).split('.')[0],
            execution_time,
            human_readable(data_scanned),
            query_cost
        ))

from

https://github.com/guardian/athena-cli/blob/0d5cc98a1cac21094077ed29cf168686ca61f10d/athena_cli.py#L217-L228

(Currently we only print `Time`.)

**Comment by ctso** [comment]
Pricing varies by region and other factors, it's also subject to change.  AWS does provide a mechanism to download pricing data, but it is a pretty complicated JSON file iirc.

I think if something like

```
query_cost = data_scanned / 1000000000000.0 * 5.0
```

It might make sense to be super clear that it is an approximate cost.

**Comment by zzl0** [comment]
Thanks for the suggestion. Yeah, this seems useful.

I have low bandwidth at the moment, I will probably work on this 2 weeks later. In the meantime, if you're interested in this, I'm happy to take a PR.

**Comment by zzl0** [comment]
I think we can add those info, please take a look at [PyAthena API](https://github.com/laughingman7743/PyAthena), athenacli is using PyAthena to query Athena database.
