### ISSUE TITLE
Ctrl-C to abort query

### ISSUE THREAD

**Issue by getaaron** [dbcli/athenacli#41]
I wanted to cancel an executing query, and tried <kbd>ctrl</kbd>-<kbd>c</kbd>. However, this quit the CLI altogether. I suggest <kbd>ctrl</kbd>-<kbd>c</kbd> during a query should abort it without quitting.

**Comment by zzl0** [comment]
Agree, this sounds a bug in athenacli. I don't have a clue off the top of my head, need to check the debug log and exception stack.

**Comment by getaaron** [comment]
Maybe this should be wrapped in `try:` / `except KeyboardInterrupt:`?

https://github.com/dbcli/athenacli/blob/master/athenacli/sqlexecute.py#L81-L82

**Comment by getaaron** [comment]
Can't reproduce this with just athenacli, I think it's something in our local environment.
