### ISSUE TITLE
Feature request: get query from stdin

### ISSUE THREAD

**Issue by jankatins** [dbcli/athenacli#53]
Most/some unix programms interpret a file named '-' as 'read from stdin'. Would you take a PR which adds this functionality to https://github.com/dbcli/athenacli/blob/master/athenacli/main.py#L651?

```python
# copied from another project which has this functionality:
    if execute == '-':
        import select
        if select.select([sys.stdin, ], [], [], 0.0)[0]:
            query = sys.stdin.read()
        else:
            raise RuntimeError("No query to execute on stdin")
    else:
       # current code which tries to read it in from file and else takes it as is
```

**Comment by zzl0** [comment]
@jankatins sorry for the late reply. This looks great, I am happy to take a PR, go for it.
