### ISSUE TITLE
Homebrew option

### ISSUE THREAD

**Issue by nitrocode** [dbcli/athenacli#59]
I'd love to install the `athenacli` using homebrew instead of pip so it doesn't clutter global dependencies

    brew install athenacli

**Comment by zzl0** [comment]
Yeah, that's a good idea. I would appreciate if you'd like to work on it and I am happy to review it.

For `pip`, we suggest install `athenacli` in a virtual environment.

**Comment by chenrui333** [comment]
FYI, I made a PR to add this into the homebrew-core. Thanks for creating this useful tool.

**Comment by zzl0** [comment]
@chenrui333 Thanks, it looks great. Just a minor comment: I am wondering if it's better to use `athenacli` as the Formula name, want to keep it the same as this project name.

**Comment by chenrui333** [comment]
> @chenrui333 Thanks, it looks great. Just a minor comment: I am wondering if it's better to use `athenacli` as the Formula name, want to keep it the same as this project name.

I was about to ask the same thing :) Based on my experience with all the `*cli` repo naming conventions, it might be better with `athena-cli` for the repo.

But I can totally change the brew formula name as well though. Just feel interesting to call out the naming convention thing :)

**Comment by zzl0** [comment]
Yeah, I agree with you. There are two reasons why we are using `athenacli` instead of `athena-cli`:

1. We are using the same naming convention as other CLIs (e.g. `pgcli`, `mycli`).
2. `athena-cli` is used by [another package](https://pypi.org/project/athena-cli/).

**Comment by chenrui333** [comment]
I see, I will update the formula name to matching with this. 👍

**Comment by chenrui333** [comment]
Should be good to go after the PR review :)

**Comment by zzl0** [comment]
👍  thanks, the CI is failing, seems need to rename `AthenaCli` to `Athenacli`

**Comment by chenrui333** [comment]
@zzl0 we shipped the formula, I think the issue is good for closure. Also worth mentioning in the README about the homebrew installation option :)

**Comment by nitrocode** [comment]
@chenrui333 nice job! Do you want to do the honors and PR the brew install command to the `README.md` ?

**Comment by zzl0** [comment]
@chenrui333 Great! @nitrocode has a good suggestion. If you don't have time to do this, I am happy to update the README and add you to the [AUTHORS](https://github.com/dbcli/athenacli/blob/master/AUTHORS.rst) file.

**Comment by chenrui333** [comment]
> @chenrui333 nice job! Do you want to do the honors and PR the brew install command to the `README.md` ?

Sounds good, doing it now. ❤️

**Comment by chenrui333** [comment]
> @chenrui333 Great! @nitrocode has a good suggestion. If you don't have time to do this, I am happy to update the README and add you to the [AUTHORS](https://github.com/dbcli/athenacli/blob/master/AUTHORS.rst) file.

Happy to take it, thanks!!

**Comment by zzl0** [comment]
Thank you @chenrui333 @nitrocode
