### ISSUE TITLE
Can't install promt-tooklit >= 3.0 alongside athenacli

### ISSUE THREAD

**Issue by renzmann** [dbcli/athenacli#71]
I regularly use both `litecli` and `athenacli` for local and remote work.  Because this tool [requires prompt-toolkit < 3.0](https://github.com/dbcli/athenacli/blob/8a097cd646086db54339a6d437e3cec5b7f1a7a4/setup.py#L22), anything else that requires prompt toolkit >= 3.0 will cause pip errors (or just won't install at all, if using poetry). `litecli` is one such tool that requires prompt-toolkit >= 3.0 that I regularly use for quick local work, and I'd prefer to have both that and athenacli in the same virtual environment, if possible.

Any chance the restriction on prompt-toolkit can be opened up to "<4.0"?

**Comment by zzl0** [comment]
@renzmann Thanks for your feedback, yeah, we can upgrade the version of `prompt-toolkit`. Since I am not using AWS now, could you help us test athenacli?

**Comment by amjith** [comment]
@renzmann I've been using `pipx` to install python applications like `black`, `litecli` and `athenacli`. This installs each python app in an isolated virtual environment so the dependencies between them don't conflict. 

https://github.com/pypa/pipx

You might find it useful. 😄

**Comment by renzmann** [comment]
> could you help us test athenacli?
@zzl0 Of course - just pytest modules under `test` or just continue using it as I normally do and report back?

> I've been using pipx
@amjith pipx is great.  My use case is a little weird though - we're trying make the analytics development environment easier to pin down in one `poetry.lock` file, if we can. That alleviates the need for each team member to manage both the poetry install process and any environment isolation overhead

**Comment by zzl0** [comment]
Hi @renzmann, just released a new version `athenacli 1.6.5` for upgrading `promt-toolkit`, feel free to re-open this if you found any bugs.
