### ISSUE TITLE
'REPL' commond error! 

### ISSUE THREAD

**Issue by ByronLeeLee** [dbcli/athenacli#72]
![image](https://user-images.githubusercontent.com/26811891/166890834-3a238d90-180f-4a9f-8d9e-ea6b200d9839.png)

**Comment by zzl0** [comment]
@ByronLeeLee thanks for your feedback. If you're feeling generous this could be an opportunity to contribute some code.

The API is deprecated in Click 8.1. Looks like you just need to change to [shutil.get_terminal_size](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size) instead.

https://click.palletsprojects.com/en/8.0.x/api/#click.get_terminal_size

**Comment by zzl0** [comment]
Fixed by https://github.com/dbcli/athenacli/pull/73
