### ISSUE TITLE
`sqlparse.compat` is not a module in `sqlparse` `0.4.x`

### ISSUE THREAD

**Issue by Moisan** [dbcli/athenacli#75]
Trying to start `athenacli` when installed with the latest `sqlparse` leads to the following error:
```    
from sqlparse.compat import text_type
ModuleNotFoundError: No module named 'sqlparse.compat'
```

**Comment by branchvincent** [comment]
It seems the issue is `sqlparse`'s latest [source distribution](https://pypi.org/project/sqlparse/#files) omits `sqlparse.compat`.  But since python2 doesn't seem to be supported here anyway, the import could be dropped in favor of using `str` directly

**Comment by zzl0** [comment]
Thank you @Moisan for reporting the error and thanks @branchvincent for fixing it
