### ISSUE TITLE
Support for default credentials.

### ISSUE THREAD

**Issue by EvilPuppetMaster** [dbcli/athenacli#9]
It is common for the official awscli tools and boto to use credentials in `~/.aws/credentials`, or in environment variables. We use this heavily to support logging in using short lived STS tokens, and avoid creating long lived secret keys, which are a security no-no.

It would be great if this tool supported using those default credentials. (And STS tokens)

**Comment by zzl0** [comment]
This is a very good idea, thank you!

**Comment by EvilPuppetMaster** [comment]
Thanks for considering it. This tool looks pretty neat too... I look forward to using it!

**Comment by zzl0** [comment]
@EvilPuppetMaster I added the support for default credentials. I only published to pypi (I haven't published it to brew and docker hub), could you install the version 0.1.2 and give it a try? and see if that's meet your expectation?

**Comment by EvilPuppetMaster** [comment]
@zzl0 yes! Works perfectly, this is awesome! Thank you!

**Comment by zzl0** [comment]
@EvilPuppetMaster I'm glad you like it, thanks for your great idea again.
